разметка главной страницы
htmlacademy-adaptive/1558671-cat-energy-21 pull request #2
Opened 2020-11-18 00:15 UTC by yarkova

2020-11-18 08:41 UTC, blckwltz requested changes
1. Нужно проверить все названия изображений, в них не должны использоваться заглавные буквы, пробелы и кириллица

2. Сейчас есть ошибки в форматировании файла, это можно увидеть [здесь](https://travis-ci.com/github/htmlacademy-adaptive/1558671-cat-energy-21/builds/202252956). Мы устанавливали плагин `editorconfig` для редактора, который как рах нужен для быстрого форматирования. Для удобства в настройках редактора можно настроить его автоматическое применение при сохранении файлов

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +        <p class="status-slogan">Занялся собой? Займись котом!</p>
1. Делать главным заголовком страниц "Промо" - не очень хорошо, ведь не понятно, о чем именно идет речь. А вот "Функциональное питание для котов" для этого подходит

2. `status-intro` и `status-slogan` логичнее заменить на `status__intro` и `status__slogan`, то есть сделать их элементами БЭМ-блока `status`

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +        <img src="img/index-background-desktop 2 (1).png" width="320" height="302" alt="кот">
Изображение кота на фоне декоративное, смысл без него не потеряется, поэтому из разметки его нужно убрать. Оно добавится позже через стили

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +        <button class="status__header__toggle" type="button">Подобрать программу</button>
Тут ошибка по БЭМ. У БЭМ- элемента не может быть еще одного элемента, поэтому использовать несколько раз `__` в одном классе нельзя

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +  <div class="losing_weigh__wrapper">
Вместо одиночных `_` лучше использовать `-`, так будет проще читать названия классов

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +</section>
1. На странице должен быть только один заголовок первого уровня

2. Изображения в этих карточках декоративные, их лучше убрать из разметки и добавить позже через стили

3. Тег `<header>` тут использовать не нужно, в этих карточках мало содержимого для этого

4. Оборачивать ссылки в тег `<p>` не обязательно

В целом обе эти карточки логичнее объединить в один `section`

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> + <h1 class="visually-hidden">Преимущества</h1>
Заголовок нужно переметить в `section`, и заменить его на `<h2>`

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +<h1 class="visually-hidden">Примеры</h1>
Заголовок нужно переметить в `section`, и заменить его на `<h2>`

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +        </dd>
Теги `<dt>` и `<dd>` должны находится внутри `<dl>`

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +      </div>
Здесь можно использовать просто параграф, без оборачивание его в `<div>`

2020-11-18 08:41 UTC, blckwltz commented on source/index.html
> +  </li>
`slider-item` логичнее заменить на `slider__item`, чтобы сделать слайды элементами БЭМ-блока `slider`

2020-11-19 19:35 UTC, yarkova reviewed
разметка главной страницы

2020-11-19 19:39 UTC, yarkova reviewed
изменения

2020-11-20 09:45 UTC, blckwltz reviewed
@yarkova Все еще не исправлены названия изображений, к следующему заданию нужно поправить.

2020-11-20 09:45 UTC, blckwltz commented on .editorconfig
> -trim_trailing_whitespace = false
@yarkova Этот файл нельзя изменять, он нужен для правильной настройки отступов в редакторе. Нужно вернуть удаленные строки

2020-11-20 09:45 UTC, blckwltz commented on source/index.html
> +        <img src="img/index-background-desktop 2 (1).png">
@yarkova Как писал в предыдущем комментарии, фоновое изображение нужно убрать из разметки

2020-11-20 09:45 UTC, blckwltz commented on source/index.html
> +  <h1>Программа для котов</h1>
@yarkova На странице должен быть только один заголовок первого уровня

2020-11-20 09:45 UTC, blckwltz commented on source/index.html
> +    <a href="#">КАТАЛОГ PRO --></a>
@yarkova Эти карточки выглядят одинаково за исключением изображений, поэтому нет смысла делать для них разные классы. Нужно привести их к одному виду.

2020-11-20 09:45 UTC, merged