разметка страницы формы
htmlacademy-adaptive/1558671-cat-energy-21 pull request #3
Opened 2020-11-25 01:11 UTC by yarkova

2020-11-25 01:15 UTC, yarkova reviewed
разметка формы

2020-11-25 07:50 UTC, blckwltz requested changes

2020-11-25 07:50 UTC, blckwltz commented on source/form.html
> +     <div class="questionnaire-form">
Не хватает самой формы (`<form>`), сейчас на странице просто набор не связанных между собой полей ввода. Нужно добавить форму и сделать так, чтобы она отправлялась.

2020-11-25 07:50 UTC, blckwltz commented on source/form.html
> +              <input type="text" name="name" id="name" placeholder="Барсик">
Для лейблов и инпутов нужно добавить классы.

2020-11-25 07:50 UTC, blckwltz commented on source/form.html
> +         <li class="choose-program__list">
Тут скорее всего опечатка. Нужно сделать по аналогии с остальными разделами.

2020-11-26 23:16 UTC, yarkova reviewed
разметка страницы форма

2020-11-27 08:07 UTC, merged