Стилизация главной страницы
htmlacademy-adaptive/1558671-cat-energy-21 pull request #5
Opened 2020-12-16 00:10 UTC by yarkova

2020-12-16 00:17 UTC, yarkova reviewed
главная страница

2020-12-16 00:24 UTC, yarkova reviewed
главная страница

2020-12-16 09:55 UTC, blckwltz requested changes
Обратите внимание, что сейчас проект не проходит проверку (команда `npm test`). Перед отправкой заданий на проверку необходимо выполнять эту команду и исправлять ошибки, если они есть.

2020-12-16 09:55 UTC, blckwltz commented on source/sass/blocks/advantages__item--clock.scss
> +}
Отдельные файлы должны быть только для блоков, но не для элементов. Соотвественно эти стили должны быть написаны в файле `advantages`, остальные также нужно переделать по аналогии. Пример правильного написания - файл `losing-weigh`

2020-12-16 09:55 UTC, blckwltz commented on source/sass/blocks/example__wrapper.scss
> +}
Глобальных стилей для тегов быть не должно (кроме тегов `html`, `body`, `a`, `img`, это разрешено критериями и их можно добавить в отдельном файле). В данном случае нужно либо переписать стили через вложенность, либо добавить для параграфа отдельный класс. Аналогичная ситуация в файлах `losing-weigh` и `weight-gain`

2020-12-16 09:55 UTC, blckwltz commented on source/sass/blocks/page.scss
> +  }
Если хотите написать стили для `body` именно по тегу, стоит делать в отдельном файле (например `global`, пример есть в лекции) и убрать у него класс. Если класс остается, то писать стили нужно именно для него.

2020-12-17 15:18 UTC, blckwltz requested changes
- Названия файлов должны совпадать с именами БЭМ-блоков, сейчас большинство названы как БЭМ-элементы (`advantages__wrapper`, `example__item` и т.д.)
- В некоторых файлах находятся стили, которых там быть не должно (например в `page-footer__contacts` есть стили для `contacts__title`, которые должны находиться в файле `contacts`)
- Все еще есть ошибки форматирования, нужно выполнить команду `npm test` и исправить их

2020-12-18 17:54 UTC, merged

2020-12-20 02:38 UTC, yarkova reviewed
Стилизация страницы формы